name: $(Build.BuildId)
 
trigger:
- main

steps:
- task: NuGetToolInstaller@1
  displayName: Install Nuget

- task: UseDotNet@2
  displayName: 'Use dotnet'
  inputs:
    version: '6.0.x'
    includePreviewVersions: true

- task: NuGetCommand@2
  displayName: Restore
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: pack
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'

- task: NuGetCommand@2
  displayName: push nuget
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'a7c0a809-2aba-45e3-a1ec-699fcb171d91'